//POPULAR MOVIE
export const SET_POPULAR_PAGE_NUMBER = 'SET_POPULAR_PAGE_NUMBER'
export const GET_POPULAR_MOVIE_REQUEST = 'GET_POPULAR_MOVIE_REQUEST'
export const GET_POPULAR_MOVIE_SUCCESS = 'GET_POPULAR_MOVIE_SUCCESS'
export const GET_POPULAR_MOVIE_ERROR = 'GET_POPULAR_MOVIE_ERROR'
export const SET_POPULAR_MOVIE_CLEAR = 'SET_POPULAR_MOVIE_CLEAR'
export const GET_POPULAR_MOVIE_ALL_SUCCESS = 'GET_POPULAR_MOVIE_ALL_SUCCESS'

//RECENT MOVIE 
export const SET_RECENT_PAGE_NUMBER = 'SET_RECENT_PAGE_NUMBER'
export const GET_RECENT_MOVIE_REQUEST = 'GET_RECENT_MOVIE_REQUEST'
export const GET_RECENT_MOVIE_SUCCESS = 'GET_RECENT_MOVIE_SUCCESS'
export const GET_RECENT_MOVIE_ERROR = 'GET_RECENT_MOVIE_ERROR'
export const SET_RECENT_MOVIE_CLEAR = 'SET_RECENT_MOVIE_CLEAR'
export const GET_RECENT_MOVIE_ALL_SUCCESS = 'GET_RECENT_MOVIE_ALL_SUCCESS'

//GENRES
export const SET_GENRE_NAME = 'SET_GENRE_NAME'
export const GET_GENRE_REQUEST = 'GET_GENRE_REQUEST'
export const GET_GENRE_SUCCESS = 'GET_GENRE_SUCCESS'
export const GET_GENRE_ERROR = 'GET_GENRE_ERROR'

//Teaser & Trailer
export const GET_TEASER_TRAILER_REQUEST = 'GET_TEASER_TRAILER_REQUEST'
export const GET_TEASER_TRAILER_SUCCESS = 'GET_TEASER_TRAILER_SUCCESS'
export const GET_TEASER_TRAILER_ERROR = 'GET_TEASER_TRAILER_ERROR'

//SEARCH MOVIE
export const SET_SEARCH_PAGE_NUMBER = 'SET_SEARCH_PAGE_NUMBER'
export const GET_SEARCH_MOVIE_REQUEST = 'GET_SEARCH_MOVIE_REQUEST'
export const GET_SEARCH_MOVIE_SUCCESS = 'GET_SEARCH_MOVIE_SUCCESS'
export const GET_SEARCH_MOVIE_ERROR = 'GET_SEARCH_MOVIE_ERROR'
export const SET_SEARCH_MOVIE_CLEAR = 'SET_SEARCH_MOVIE_CLEAR'

//THEME
export const SET_THEME_MODE = 'SET_THEME_MODE'
export const GET_THEME_LOADING = 'GET_THEME_LOADING'
export const GET_THEME_ERROR = 'GET_THEME_LOADING'

//FAVORITE
export const GET_FAVORITE_MOVIE_REQUEST = 'GET_FAVORITE_MOVIE_REQUEST'
export const GET_FAVORITE_MOVIE_SUCCESS = 'GET_FAVORITE_MOVIE_SUCCESS'
export const GET_FAVORITE_MOVIE_ERROR = 'GET_FAVORITE_MOVIE_ERROR'
export const SET_FAVORITE_MOVIE_CLEAR = 'SET_FAVORITE_MOVIE_CLEAR'
export const SET_FAVORITE_MOVIE_ITEM = 'SET_FAVORITE_MOVIE_ITEM'
export const DATABASE_CHANGED = 'DATABASE_CHANGED'
